/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package lv.vizzual.numuri;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int logo_amigo=0x7f020001;
        public static final int logo_bite=0x7f020002;
        public static final int logo_izzi=0x7f020003;
        public static final int logo_lattelecom=0x7f020004;
        public static final int logo_lmt=0x7f020005;
        public static final int logo_tele2=0x7f020006;
        public static final int logo_triatel=0x7f020007;
        public static final int sdcard_bg=0x7f020008;
        public static final int toast_bg=0x7f020009;
    }
    public static final class id {
        public static final int networkOperatorValue=0x7f050002;
        public static final int toast_image=0x7f050001;
        public static final int toast_root=0x7f050000;
    }
    public static final class layout {
        public static final int toast=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int cancel=0x7f040004;
        public static final int continue_download=0x7f040003;
        public static final int ok=0x7f040006;
        public static final int update_complete_desc=0x7f04000a;
        public static final int update_complete_title=0x7f040009;
        public static final int update_failed_desc=0x7f040008;
        public static final int update_failed_title=0x7f040007;
        public static final int update_start_desc=0x7f040002;
        public static final int update_start_title=0x7f040001;
        public static final int updating_data=0x7f040005;
    }
}
